#!/usr/bin/env node
var child_process = require('child_process');
var fs = require('fs');
var path = require('path');

var qtmsdir = process.cwd();
var qtmsutilDir = null;
[process.cwd(), path.join(qtmsdir, 'qtms-util')].forEach(p => {
    if (qtmsutilDir === null) {
        try {
            var stat = fs.statSync(path.join(p, 'qtms-util.js'));
            if (stat.isFile()) {
                qtmsutilDir = p;
            }
        }
        catch (error) {
            // Intentionally ignoring errors while searching for module file.
        }
    }
});
if (!qtmsutilDir) {
    console.error('Fatal Error: Unable to locate qtms-util.js, cannot proceed.');
    process.exit(1);
}
//console.log('qtmsutilDir = %s', qtmsutilDir);
try {
    var stat = fs.statSync(path.join(qtmsutilDir, 'node_modules'));
    stat.isDirectory()
        ? qtmsutil()
        : npmInstall(qtmsutil);
}
catch (error) {
    console.warn('Warning: Unable to locate node_modules, attempting to install.\n', error);
    npmInstall(qtmsutil);
}

function npmInstall(callback) {
    process.chdir(qtmsutilDir);
    var npm = require('npm');
    npm.on('log', function(message) {
        console.log(message);
    })
    npm.load({ loaded: false }, function(error) {
        return error
            ? console.error('npm.load| error:', error)
            : npm.commands.install(function(error) {
                return error
                    ? console.error('npm.install| error:', error)
                    : qtmsutil();
            });
    });
}

function qtmsutil() {
    try {
        // if (process.argv.indexOf('dev') < 1) {
        //     process.argv.splice(process.argv.findIndex(function(x) { return /helper2?(\.js)?$/.test(x); }) + 1, 0, 'dev');
        // }
        process.chdir(qtmsdir);
        require(path.join(qtmsutilDir, 'qtms-util.js'));
    }
    catch (error) {
        console.error('Error: Failed while executing qtms-util.js.\n', error);
        process.exit(1);
    }
}
